; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "e-Fatura Edit"
#define MyAppVersion "1.7"
#define MyAppPublisher "Zafer Bilgisayar"
#define MyAppURL "https://www.zaferbilgisayare.com/"
#define MyAppExeName "e-FaturaEdit.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{17A8E6D6-7FEF-459B-BA25-87AF93F0B714}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=c:\e-FaturaEdit\
DefaultGroupName={#MyAppName}
LicenseFile=D:\projeler\DXApplication3\DXApplication5\Lisans.rtf
OutputDir=D:\projeler\DXApplication3\Output
OutputBaseFilename=e-FaturaEditsetup
SetupIconFile=D:\projeler\DXApplication3\DXApplication5\icons8_invoice_64_LGi_icon.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "turkish"; MessagesFile: "compiler:Languages\Turkish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\e-FaturaEdit.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\CefSharp.BrowserSubprocess.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\CefSharp.BrowserSubprocess.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\CefSharp.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\CefSharp.Core.Runtime.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\CefSharp.Core.Runtime.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\CefSharp.Core.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\CefSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\CefSharp.WinForms.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\CefSharp.WinForms.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\CefSharp.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\chrome_100_percent.pak"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\chrome_200_percent.pak"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\chrome_elf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\d3dcompiler_47.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.BonusSkins.v14.2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.Data.v14.2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.Data.v14.2.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.Office.v14.2.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.Office.v14.2.Core.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.Printing.v14.2.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.Printing.v14.2.Core.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.RichEdit.v14.2.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.RichEdit.v14.2.Core.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.Sparkline.v14.2.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.Sparkline.v14.2.Core.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.Utils.v14.2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.Utils.v14.2.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.XtraBars.v14.2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.XtraBars.v14.2.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.XtraEditors.v14.2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.XtraEditors.v14.2.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.XtraLayout.v14.2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.XtraLayout.v14.2.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.XtraNavBar.v14.2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.XtraNavBar.v14.2.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.XtraPrinting.v14.2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.XtraPrinting.v14.2.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.XtraTreeList.v14.2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\DevExpress.XtraTreeList.v14.2.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\diz.xslt"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\e-FaturaEdit.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\e-FaturaEdit.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\e-FaturaEdit.vshost.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\e-FaturaEdit.vshost.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\eFaturaLicense.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\fatura.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\ICSharpCode.TextEditor.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\ICSharpCode.TextEditorEx.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\icudtl.dat"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\IKVM.OpenJDK.Charsets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\IKVM.OpenJDK.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\IKVM.OpenJDK.Localedata.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\IKVM.OpenJDK.Text.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\IKVM.OpenJDK.Util.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\IKVM.OpenJDK.XML.API.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\IKVM.Runtime.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\libcef.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\libEGL.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\libGLESv2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\QLicense.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\QLicense.Windows.Controls.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\resources.pak"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\saxon-he-10.9.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\saxon-he-api-10.9.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\saxon-he-api-10.9.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\snapshot_blob.bin"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\v8_context_snapshot.bin"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\vk_swiftshader.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\vk_swiftshader_icd.json"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\vulkan-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\projeler\DXApplication3\DXApplication5\Assets\*"; DestDir: "{app}\Assets\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\XMLDataFiles\*"; DestDir: "{app}\XMLDataFiles\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\projeler\DXApplication3\DXApplication5\bin\x86\Release\locales\*"; DestDir: "{app}\locales\"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\projeler\DXApplication3\DXApplication5\Lisans.rtf"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

